/** 退出登录应被清理 */
export enum StorageType { // 储存类型
	USER_INFO = 'userInfo',
	LOGIN_INFO = 'loginInfo',
	COOKIE = 'cookie',
	DATA_GROUP = 'DATA_GROUP',
	DATA_PROJECT = 'DATA_PROJECT',
	DATA_DIR = 'DATA_DIR',
	DATA_DIR_AND_ITEM = 'DATA_DIR_AND_ITEM',
	DATA_ITEM = 'DATA_ITEM',
	LOGIN_STAMP = 'LOGIN_STAMP',
	WEBVIEW_DONE = 'WEBVIEW_DONE'
}

/** 退出登录还要保留 */
export enum StorageTypeLong {
	SERVER_URL = 'SERVER_URL',
	API_TYPE_LIST = 'API_TYPE_LIST',
	LOGIN_BY_LDAP = 'LOGIN_BY_LDAP'
}

export enum AllStorageType {
	USER_INFO = 'userInfo',
	LOGIN_INFO = 'loginInfo',
	COOKIE = 'cookie',
	DATA_GROUP = 'DATA_GROUP',
	DATA_PROJECT = 'DATA_PROJECT',
	DATA_DIR = 'DATA_DIR',
	DATA_DIR_AND_ITEM = 'DATA_DIR_AND_ITEM',
	DATA_ITEM = 'DATA_ITEM',
	LOGIN_STAMP = 'LOGIN_STAMP',
	WEBVIEW_DONE = 'WEBVIEW_DONE',
	SERVER_URL = 'SERVER_URL',
	API_TYPE_LIST = 'API_TYPE_LIST',
	LOGIN_BY_LDAP = 'LOGIN_BY_LDAP'
}
